language: c
dist: xenial
group: edge
dist: focal
virt: vm
sudo: required
arch:
  - amd64
  - arm64-graviton2
branches:
  only:
  - master
  - develop
os:
  - linux
git:
  submodules: false
services:
  - xvfb
before_install:
  - git submodule update --init --recursive
compiler:
  #- clang
  - gcc
env:
  - TRAVIS_PYTHON_VERSION=3.9
notifications:
  email:
    recipients:
      - stan-buildbot@googlegroups.com
    on_success: change
    on_failure: always
install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh 
